#!/bin/bash

source kirbycli

read -p "What is the Server Name ?" servername
read -p "Ready to init $servername ?" ok

# lanch kirby installation
read -p "Install Kirby from github (y/n)?" choice
case "$choice" in
  y|Y ) ./kirbyinstall $htdocs$servername ${servername:0:10};;
  n|N ) mkdir $htdocs$servername $htdocs$servername"/content/"; git init $htdocs$servername ;;
  * ) echo "invalid";;
esac

createVhost $servername

# Dropbox symbolic link
createSharedDir $servername

read -p "Init git prod repository (y/n)?" choice
case "$choice" in
  y|Y ) initProdRepo $servername;;
  n|N ) echo "continue";;
  * ) echo "invalid";;
esac